var GAME_LEVELS = [
	[
	  "                      ",
	  "                      ",
	  "  x              = x  ",
	  "  x         o o    x  ",
	  "  x @      xxxxx   x  ",
	  "  xxxxx            x  ",
	  "      x!!!!!!!!!!!!x  ",
	  "      xxxxxxxxxxxxxx  ",
	  "                      "
	],
	[
		"                   ",
		"                   ",
		"  @         vv     ",
		"  xx               ",
		"                   ",
		"        o          ",
		"       xxx         ",
		"                   ",
		"                o  ",
		"               xxx ",
		"=                  ",
		"        o          ",
		"       xxx         ",
		"                   ",
		"   o               ",
		"  xxx              ",
		"                  =",
		"          o        ",
		"         xxx       ",
		"                   ",
		"                   ",
		"!!!!!!!!!!!!!!!!!!!",
		"xxxxxxxxxxxxxxxxxxx",
	],
	[
		"                                                    ",
		"                                                    ",
		"                                                    ",
		"                                                    ",
		"                      xxxxxxx                       ",
		"                    xxx     xxx                     ",
		"                   xx         xxx                   ",
		"                  x       oo    xx                  ",
		"                 xxo     xxxo    xx  xx             ",
		"                  xxo       xo            xx        ",
		"                   xxo     @xx=                    =",
		"                    xx     xx    oooo               ",
		"                     xx!!xx  xxxxxxxxx              ",
		"                      vxxv                          ",
		"                                                    ",
		"                                                    ",
		"                                                    ",

	]
];